### ISSUE TITLE
ResponseRaw error

### ISSUE THREAD

**Issue by vwwv** [singpolyma/wai-util#5]
hi,
Great library! I was a bit shocked when I saw:
```
mapHeaders _ (ResponseRaw _ _) = error "Cannot mapHeaders of Wai.Interal.ResponseRaw"
```
is there a reason it can not be implemented like:
```
mapHeader f (ResponseRaw acc resp)   = ResponseRaw acc (f resp)
```
?

**Comment by vwwv** [comment]
If you wan I  can make a PR with that change.

**Comment by singpolyma** [comment]
Is `resp` just headers?

**Comment by vwwv** [comment]
sorry my bad, I meant:
```
mapHeaders f (ResponseRaw acc resp)   = ResponseRaw acc (mapHeaders f resp)
```
I tried and compiled, and I think it would work; but have not test yet with real examples.

**Comment by vwwv** [comment]
```
resp :: Response
acc  :: IO ByteString -> (ByteString -> IO ()) -> IO ()
```

**Comment by singpolyma** [comment]
Seems better than `error` for sure -- send the PR :)

**Comment by vwwv** [comment]
Great, I'll send it in a moment.
